baseURL = "https://kunaalahuja.github.io/"
languageCode = "en-us"
title = "Kunaal Ahuja"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "Kunaal Ahuja"
    description = "Geek | Data Enthusiast | Traveller | Sports Lover"
    email = "kunaal92@gmail.com"
    phone = "+1 678 848 8960"
    address = "Atlanta, Georgia"
    year = 2020
    avatar = "images/guy.jpg"
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.disqus]
    site = ""

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = ""

[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/kunaal-ahuja"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = false
    network = "linkedin"
[[params.social]]
    title = "github"
    url = "https://github.com/kunaalahuja"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
    title = "facebook"
    url = "https://www.facebook.com/kunaal92"
    icon = "fab fa-facebook-square"
    footer = true
    sharethis = false
    network = "facebook"
[[params.social]]
    title = "instagram"
    url = "https://www.instagram.com/kunaalahuja"
    icon = "fab fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
    title = "twitter"
    url = "https://twitter.com/kunaalahuja"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = false
    network = "twitter"
[[params.social]]
    title = "email"
    url = "mailto:kunaal92@gmail.com"
    icon = "fab fa-envelope-square"
    footer = false
    sharethis = false
    network = "email"
